name: GH-pages Deployment
on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download submodules
        run: git submodule update --init
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install pip build setuptools wheel request -U
          python sync.py
          pip install -e .
      - name: Build & Pack
        run: |
          python entry.py --version
          rm -fr build
          rym pack reveal_yaml -o build
          cp reveal_yaml/schema.json build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
      - name: Pack
        run: python -m build --wheel
      - name: Publish package
        if: github.repository == 'KmolYuan/reveal-yaml' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.TWINE_USERNAME }}
          password: ${{ secrets.TWINE_PASSWORD }}
          skip_existing: true
